export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";
export const GET_CONTACTS_LOAD = "GET_CONTACTS_LOAD";

export const GET_ONE_CONTACT_SUCCESS = "GET_ONE_CONTACT_SUCCESS";
